---
# tasks file for ansible-role-dbug
#
#
#

- name: Dump all Ansible variables
  template: src=dump_variables.j2 dest={{ dbug_variables }}

- name: Save dumpfile locally
  fetch: "src={{ dbug_variables }} dest={{ dbug_host_destination }} flat={{ dbug_flat_mode }}"
  when: "dbug_host_destination is defined"

- name: Remove dumpfile on the guest
  file: path={{ dbug_variables }} state=absent
  when: "dbug_host_destination is defined"
  
  #
